import { Deck } from '../types';

export const SAMPLE_DECKS: Deck[] = [
  {
    id: 'deck_postgres_arch',
    title: 'Архитектура PostgreSQL',
    description: 'Внутреннее устройство Postgres: WAL, MVCC, буферный пул, индексы B-Tree/GIN и вакуум.',
    icon: 'Database',
    color: 'from-blue-600 to-indigo-700',
    tags: ['Databases', 'PostgreSQL', 'Backend', 'DBA'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cards: [
      {
        id: 'pg_1',
        type: 'qa',
        question: 'Что такое MVCC (Multi-Version Concurrency Control) в PostgreSQL и зачем он нужен?',
        answer: 'MVCC позволяет нескольким транзакциям одновременно читать и писать данные без взаимной блокировки за счет создания версий строк (tuples) с метаданными xmin/xmax.',
        explanation: 'Читатели не блокируют писателей, а писатели не блокируют читателей. Обновление (UPDATE) в Postgres создаёт новую версию строки, а не перезаписывает старую.',
        tags: ['MVCC', 'Concurrency'],
        repetitions: 0,
        interval: 0,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        lastReviewedAt: null,
        history: [],
      },
      {
        id: 'pg_2',
        type: 'cloze',
        question: 'Механизм протоколирования транзакций',
        answer: 'Запись перед записью (WAL)',
        clozeText: 'Для обеспечения свойства Durability (ACID) PostgreSQL использует лог {{c1::WAL (Write-Ahead Logging)}}, в который изменения записываются строго ДО их сброса на диск.',
        explanation: 'Если произойдёт сбой питания, Postgres восстановит состояние базы, проиграв WAL с последнего чекпоинта.',
        tags: ['ACID', 'WAL', 'Durability'],
        repetitions: 0,
        interval: 0,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        lastReviewedAt: null,
        history: [],
      },
      {
        id: 'pg_3',
        type: 'code',
        question: 'Почему этот запрос выполняет Full Table Scan вместо использования B-Tree индекса?',
        codeSnippet: 'SELECT * FROM users WHERE LOWER(email) = \'user@example.com\';',
        answer: 'Потому что стандартный B-Tree индекс создан по email, а функция LOWER() модифицирует значение в запросе. Нужно создать функциональный индекс.',
        explanation: 'Решение: CREATE INDEX idx_users_lower_email ON users (LOWER(email));',
        tags: ['Indexing', 'Performance', 'SQL'],
        repetitions: 0,
        interval: 0,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        lastReviewedAt: null,
        history: [],
      },
      {
        id: 'pg_4',
        type: 'mcq',
        question: 'Какой тип индекса в PostgreSQL идеально подходит для поиска элементов внутри JSONB массивов и полнотекстового поиска (Full-Text Search)?',
        answer: 'GIN (Generalized Inverted Index)',
        options: ['B-Tree', 'BRIN', 'GIN (Generalized Inverted Index)', 'Hash Index'],
        correctOptionIndex: 2,
        explanation: 'GIN расшифровывается как Generalized Inverted Index (обобщенный инвертированный индекс). Он индексирует составляющие элементы (ключи/элементы массива).',
        tags: ['Indexes', 'JSONB'],
        repetitions: 0,
        interval: 0,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        lastReviewedAt: null,
        history: [],
      },
      {
        id: 'pg_5',
        type: 'qa',
        question: 'Какую главную задачу выполняет процесс VACUUM в PostgreSQL?',
        answer: 'Очистка «мёртвых» строк (dead tuples), оставшихся после UPDATE/DELETE, предотвращение переполнения счетчика транзакций (Transaction ID Wraparound) и обновление статистики для планировщика.',
        explanation: 'Обычный VACUUM возвращает место внутри страниц БД, а VACUUM FULL сжимает таблицы, но блокирует их на запись.',
        tags: ['Vacuum', 'Maintenance'],
        repetitions: 0,
        interval: 0,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        lastReviewedAt: null,
        history: [],
      },
    ],
  },
  {
    id: 'deck_risk_management',
    title: 'Управление рисками & Финансовый менеджмент',
    description: 'Оценка операционных и рыночных рисков, метрики VaR, стратегия хеджирования и матрица рисков.',
    icon: 'ShieldAlert',
    color: 'from-amber-600 to-rose-600',
    tags: ['Risk', 'Finance', 'Management', 'Business'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cards: [
      {
        id: 'risk_1',
        type: 'qa',
        question: 'Что показывает метрика Value at Risk (VaR) в финансовом менеджменте?',
        answer: 'VaR оценивает максимальный ожидаемый убыток портфеля за заданный период времени при определенном доверительном уровне (например, 95% или 99%).',
        explanation: 'Пример: VaR в $1 млн на 1 день с 95% надежностью означает, что с вероятностью 95% дневной убыток не превысит $1 млн.',
        tags: ['VaR', 'Metrics'],
        repetitions: 0,
        interval: 0,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        lastReviewedAt: null,
        history: [],
      },
      {
        id: 'risk_2',
        type: 'cloze',
        question: '4 базовые стратегии работы с рисками',
        answer: 'Избегание, Снижение, Передача, Принятие',
        clozeText: '4 фундаментальные стратегии реагирования на риски: {{c1::Избегание (Avoidance)}}, {{c1::Снижение (Mitigation)}}, {{c1::Передача (Transfer)}} (например, страхование) и {{c1::Принятие (Acceptance)}}.',
        explanation: 'Выбор стратегии зависит от вероятности наступления риска (Impact vs Probability).',
        tags: ['Strategy', 'Framework'],
        repetitions: 0,
        interval: 0,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        lastReviewedAt: null,
        history: [],
      },
      {
        id: 'risk_3',
        type: 'mcq',
        question: 'Что из перечисленного является примером передачи (Transfer) риска?',
        answer: 'Покупка страхового полиса или использование опционов на бирже',
        options: [
          'Установка пожарной сигнализации на складе',
          'Отказ от выхода на высокорискованный рынок',
          'Покупка страхового полиса или использование опционов на бирже',
          'Создание финансового резервного фонда компании'
        ],
        correctOptionIndex: 2,
        explanation: 'Передача риска перекладывает финансовые последствия на третью сторону (страховая компания, контрагент по опциону).',
        tags: ['Insurance', 'Hedging'],
        repetitions: 0,
        interval: 0,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        lastReviewedAt: null,
        history: [],
      },
    ],
  },
  {
    id: 'deck_system_design',
    title: 'System Design & Distributed Systems',
    description: 'Архитектура высоконагруженных систем, CAP-теорема, консистентное хэширование и паттерны отказоустойчивости.',
    icon: 'Network',
    color: 'from-emerald-600 to-teal-700',
    tags: ['System Design', 'Architecture', 'Microservices'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cards: [
      {
        id: 'sd_1',
        type: 'qa',
        question: 'Сформулируйте смысл теоремы CAP для распределенных систем.',
        answer: 'Распределенная система при наличии сетевого сбоя (Partition tolerance) может одновременно гарантировать только одно из двух: либо строгую согласованность (Consistency), либо высокую доступность (Availability).',
        explanation: 'В реальных сетях сетевые сбои (P) неизбежны, поэтому система выбирает путь CP (Consul, HBase) или AP (Cassandra, DynamoDB).',
        tags: ['CAP Theorem', 'Distributed Systems'],
        repetitions: 0,
        interval: 0,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        lastReviewedAt: null,
        history: [],
      },
      {
        id: 'sd_2',
        type: 'cloze',
        question: 'Балансировка ключей в распределенном кэше',
        answer: 'Consistent Hashing',
        clozeText: 'Для минимизации перераспределения ключей при добавлении или удалении нод в кэш-кластере используется алгоритм {{c1::Consistent Hashing (Согласованное хэширование)}}.',
        explanation: 'При изменении количества серверов N перераспределяется всего 1/N часть всех ключей.',
        tags: ['Caching', 'Hashing'],
        repetitions: 0,
        interval: 0,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        lastReviewedAt: null,
        history: [],
      },
      {
        id: 'sd_3',
        type: 'qa',
        question: 'Как работает паттерн Circuit Breaker (Предохранитель)?',
        answer: 'Circuit Breaker мониторит количество ошибок при вызовах стороннего сервиса. Если порог ошибок превышен, он размыкает цепь (Open) и мгновенно возвращает фолбэк, не нагружая упавший сервис.',
        explanation: 'Состояния: Closed (нормальная работа) -> Open (сбои, вызовы блокируются) -> Half-Open (пробные запросы).',
        tags: ['Resilience', 'Patterns'],
        repetitions: 0,
        interval: 0,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        lastReviewedAt: null,
        history: [],
      },
    ],
  },
  {
    id: 'deck_react_ts',
    title: 'TypeScript & React Internals',
    description: 'Продвинутая типизация, React 19 Fiber, Server Components и правила оптической производительности.',
    icon: 'Code',
    color: 'from-violet-600 to-purple-700',
    tags: ['React', 'TypeScript', 'Frontend'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    cards: [
      {
        id: 'ts_1',
        type: 'code',
        question: 'Что выведет TypeScript для типа ExtractAdminStatus?',
        codeSnippet: `type User = 
  | { role: 'admin'; permissions: string[] }
  | { role: 'guest'; anonymous: boolean };

type AdminUser = Extract<User, { role: 'admin' }>;`,
        answer: 'AdminUser будет равен строго { role: \'admin\'; permissions: string[] }, используя механизмы Discriminated Union.',
        explanation: 'Extract отфильтровывает члены объединения, подходящие под указанный литеральный шаблон.',
        tags: ['TypeScript', 'Unions'],
        repetitions: 0,
        interval: 0,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        lastReviewedAt: null,
        history: [],
      },
      {
        id: 'ts_2',
        type: 'qa',
        question: 'Почему в React нельзя передавать нестабильные функции или объекты прямо в массив зависимостей useEffect?',
        answer: 'Потому что в JavaScript встроенное сравнение (Object.is) проверяет ссылки. Новые объекты/функции, создаваемые при каждом рендере, будут вызывать бесконечный цикл перерисовки.',
        explanation: 'Для решения используйте useCallback, useMemo или объявляйте вспомогательные функции вне тела компонента.',
        tags: ['React', 'Hooks', 'useEffect'],
        repetitions: 0,
        interval: 0,
        easeFactor: 2.5,
        dueDate: new Date().toISOString(),
        lastReviewedAt: null,
        history: [],
      },
    ],
  },
];
